from fastapi import FastAPI
from app.api.routes_health import (router as health_check)
from app.api.routes_requirements import (router as requirement_router)
from app.api.routes_projects import (router as project_router)
from app.api.routes_rag import (router as rag_router)
from app.api.routes_code import (router as  code_router)
from app.api.routes_plans import (router as plan_router)
from app.api.routes_workflow import (router as workflow_router)
app = FastAPI(title="Frontend Agent Workflow Platform")

app.include_router(health_check)
app.include_router(requirement_router)
app.include_router(project_router)
app.include_router(rag_router)
app.include_router(code_router)
app.include_router(plan_router)
app.include_router(workflow_router)